### ISSUE TITLE
Make clipboard an optional feature

### ISSUE THREAD

**Issue by PlexSheep** [asasine/spongebob#14]
`arboard` adds a lot of dependencies and might be unnecessary when the user can just pipe the stdout into a command that will copy the stdin to the clipboard. For that reason, I propose that `arboard` should be an optional feature. Additionally, if used on platforms without GUI, users might run into #8 and get a warning as those don't tend to have system clipboards.

**Comment by asasine** [comment]
I think this is a good idea. If there's a decent utility for most/all operating systems, and they can be documented in the help text and/or README, I think there's a case to be made for removing `arboard` entirely.

**Comment by PlexSheep** [comment]
I'm only using wayland on Linux, but that has `wl-copy` which works pretty good. I believe macos also has something. X11 has xclip, but I'm not sure about windows (is windows even supported by this crate?)

**Comment by asasine** [comment]
It seems like there are utilities on all major OS's for piping to clipboard:

- Linux (Wayland): `spongebob foo | wl-copy`
- Linux (X11): `spongebob foo | xclip`
- Windows: `spongebob foo | clip`
- macOS: `spongebob foo | pbcopy`
- WSL: `spongebob foo | clip.exe`

I think I'll update docs and help text to redirect users to those utilities and forego the copy feature (and the arboard dependency).
