### ISSUE TITLE
Document what the `goodboye` binary does

### ISSUE THREAD

**Issue by PlexSheep** [asasine/spongebob#15]
It has the same help text as spongebob, which is also the name of the crate? After compiling it, it seems to just replace ~~regular western text with wide style japanese romaji~~ add spaces between latin letters?

~~"Foo Bar" => "Ｆｏｏ　Ｂａｒ"~~
"Foo Bar" => "F o o B a r"

Perhaps it would be better to move the goodboye binary into a different crate, although the differences in code are minor?

**Comment by asasine** [comment]
The intent was to add spaces between letters, yes. I don't have a lot of experience working with non-Latin alphabets so I'll admit that I didn't consider its use there. To be honest, I didn't really consider this crate to ever get used by anyone but me 😅

At the very least, I'll add some documentation for it.

**Comment by PlexSheep** [comment]
Yeah, I am learning Japanese, so I kind of just assumed it was wide letters when starting to write this issue. I filed it because I was pretty confused what this other binary in spongebob was, and the help menu said the same thing.
