### ISSUE TITLE
Clipboard functionality doesn't work on Linux

### ISSUE THREAD

**Issue by asasine** [asasine/spongebob#8]
The problem stems from the arboard package 1Password/arboard#153

**Comment by PlexSheep** [comment]
It works on pop!_os with gnome/wayland. I suspect it's only some systems that don't work, as the GNU/Linux space is not homogenous.

**Comment by asasine** [comment]
Thanks for the report! I've noticed the problem primarily on WSL. I can't confirm other systems as I haven't found a reason to add this utility to production servers yet :D

**Comment by PlexSheep** [comment]
Just to be clear, I'm also not using it on a server, no real use for that.
